package com.example.d;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.view.WindowManager;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.Toast;

import com.android.volley.AuthFailureError;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;

import java.util.HashMap;
import java.util.Map;

public class cseAdd extends AppCompatActivity {


        AutoCompleteTextView txtname, txtroll, sec;
        Button btn;

        private static final String[] CSE = new String[]{

                "19NU1A0501",
                "19NU1A0502",
                "19NU1A0503",
                "19NU1A0504",
                "19NU1A0505",
                "19NU1A0506",
                "19NU1A0507",
                "19NU1A0508",
                "19NU1A0509",
                "19NU1A0510",
                "19NU1A0511",
                "19NU1A0512",
                "19NU1A0513",
                "19NU1A0514",
                "19NU1A0515",
                "19NU1A0516",
                "19NU1A0517",
                "19NU1A0518",
                "19NU1A0519",
                "19NU1A0520",
                "19NU1A0521",
                "19NU1A0522",
                "19NU1A0523",
                "19NU1A0524",
                "19NU1A0525",
                "19NU1A0526",
                "19NU1A0527",
                "19NU1A0528",
                "19NU1A0529",
                "19NU1A0530",
                "19NU1A0531",
                "19NU1A0532",
                "19NU1A0533",
                "19NU1A0534",
                "19NU1A0535",
                "19NU1A0536",
                "19NU1A0537",
                "19NU1A0538",
                "19NU1A0539",
                "19NU1A0540",
                "19NU1A0541",
                "19NU1A0542",
                "19NU1A0543",
                "19NU1A0544",
                "19NU1A0545",
                "19NU1A0546",
                "19NU1A0547",
                "19NU1A0548",
                "19NU1A0549",
                "19NU1A0550",
                "19NU1A0551",
                "19NU1A0552",
                "19NU1A0553",
                "19NU1A0554",
                "19NU1A0555",
                "19NU1A0556",
                "19NU1A0557",
                "19NU1A0558",
                "19NU1A0559",
                "19NU1A0560",
                "19NU1A0561",
                "19NU1A0562",
                "19NU1A0563",
                "19NU1A0564",
                "19NU1A0565",
                "19NU1A0566",
                "19NU1A0567",
                "19NU1A0568",
                "19NU1A0569",
                "19NU1A0570",
                "19NU1A0571",
                "19NU1A0572",
                "19NU1A0573",
                "19NU1A0574",
                "19NU1A0575",
                "19NU1A0576",
                "19NU1A0577",
                "19NU1A0578",
                "19NU1A0579",
                "19NU1A0580",
                "19NU1A0581",
                "19NU1A0582",
                "19NU1A0583",
                "19NU1A0584",
                "19NU1A0585",
                "19NU1A0586",
                "19NU1A0587",
                "19NU1A0588",
                "19NU1A0589",
                "19NU1A0590",
                "19NU1A0591",
                "19NU1A0592",
                "19NU1A0593",
                "19NU1A0594",
                "19NU1A0595",
                "19NU1A0596",
                "19NU1A0597",
                "19NU1A0598",
                "19NU1A0599",
                "19NU1A0600",
                "19NU1A0601",
                "19NU1A0602",
                "19NU1A0603",
                "19NU1A0604",
                "19NU1A0605",
                "19NU1A0606",
                "19NU1A0607",
                "19NU1A0608",
                "19NU1A0609",
                "19NU1A0610",
                "19NU1A0611",
                "19NU1A0612",
                "19NU1A0613",
                "19NU1A0614",
                "19NU1A0615",
                "19NU1A0616",
                "19NU1A0617",
                "19NU1A0618",
                "19NU1A0619",
                "19NU1A0620",
                "19NU1A0621",
                "19NU1A0622",
                "18NU1A0501",
                "18NU1A0502",
                "18NU1A0503",
                "18NU1A0504",
                "18NU1A0505",
                "18NU1A0506",
                "18NU1A0507",
                "18NU1A0508",
                "18NU1A0509",
                "18NU1A0510",
                "18NU1A0511",
                "18NU1A0512",
                "18NU1A0513",
                "18NU1A0514",
                "18NU1A0515",
                "18NU1A0516",
                "18NU1A0517",
                "18NU1A0518",
                "18NU1A0519",
                "18NU1A0520",
                "18NU1A0521",
                "18NU1A0522",
                "18NU1A0524",
                "18NU1A0525",
                "18NU1A0526",
                "18NU1A0527",
                "18NU1A0528",
                "18NU1A0529",
                "18NU1A0530",
                "18NU1A0531",
                "18NU1A0532",
                "18NU1A0533",
                "18NU1A0534",
                "18NU1A0535",
                "18NU1A0536",
                "18NU1A0537",
                "18NU1A0538",
                "18NU1A0539",
                "18NU1A0540",
                "18NU1A0541",
                "18NU1A0542",
                "18NU1A0543",
                "18NU1A0544",
                "18NU1A0545",
                "18NU1A0546",
                "18NU1A0547",
                "18NU1A0548",
                "18NU1A0549",
                "18NU1A0550",
                "18NU1A0551",
                "18NU1A0552",
                "18NU1A0553",
                "18NU1A0554",
                "18NU1A0555",
                "18NU1A0556",
                "18NU1A0557",
                "18NU1A0558",
                "18NU1A0559",
                "18NU1A0560",
                "17NU1A0504",
                "18NU1A0561",
                "18NU1A0563",
                "18NU1A0564",
                "18NU1A0565",
                "18NU1A0566",
                "18NU1A0567",
                "18NU1A0568",
                "18NU1A0569",
                "18NU1A0570",
                "18NU1A0571",
                "18NU1A0572",
                "18NU1A0573",
                "18NU1A0574",
                "18NU1A0575",
                "18NU1A0576",
                "18NU1A0577",
                "18NU1A0578",
                "18NU1A0579",
                "18NU1A0580",
                "18NU1A0581",
                "18NU1A0582",
                "18NU1A0583",
                "18NU1A0584",
                "18NU1A0585",
                "18NU1A0586",
                "18NU1A0587",
                "18NU1A0588",
                "18NU1A0589",
                "18NU1A0590",
                "18NU1A0591",
                "18NU1A0592",
                "18NU1A0593",
                "18NU1A0594",
                "18NU1A0595",
                "18NU1A0596",
                "18NU1A0597",
                "18NU1A0598",
                "18NU1A0599",
                "18NU1A05A0",
                "18NU1A05A1",
                "18NU1A05A2",
                "18NU1A05A3",
                "18NU1A05A4",
                "18NU1A05A5",
                "18NU1A05A6",
                "19NU5A0501",
                "19NU5A0502",
                "19NU5A0503",
                "19NU5A0504",
                "19NU5A0505",
                "19NU5A0506",
                "19NU5A0507",
                "19NU5A0508",
                "19NU5A0509",
                "19NU5A0510",
                "19NU5A0511",
                "17NU1A0501",
                "17NU1A0502",
                "17NU1A0503",
                "17NU1A0505",
                "17NU1A0506",
                "17NU1A0507",
                "17NU1A0508",
                "17NU1A0509",
                "17NU1A0510",
                "17NU1A0511",
                "17NU1A0512",
                "17NU1A0513",
                "17NU1A0514",
                "17NU1A0515",
                "17NU1A0516",
                "17NU1A0517",
                "17NU1A0518",
                "17NU1A0519",
                "17NU1A0520",
                "17NU1A0521",
                "17NU1A0522",
                "17NU1A0523",
                "17NU1A0524",
                "17NU1A0525",
                "17NU1A0526",
                "17NU1A0527",
                "17NU1A0528",
                "17NU1A0529",
                "17NU1A0530",
                "17NU1A0531",
                "17NU1A0532",
                "17NU1A0533",
                "17NU1A0534",
                "17NU1A0536",
                "17NU1A0537",
                "17NU1A0538",
                "17NU1A0539",
                "17NU1A0540",
                "17NU1A0541",
                "17NU1A0542",
                "17NU1A0543",
                "17NU1A0544",
                "17NU1A0545",
                "17NU1A0546",
                "17NU1A0547",
                "17NU1A0548",
                "17NU1A0549",
                "17NU1A0550",
                "17NU1A0551",
                "17NU1A0552",
                "17NU1A0553",
                "17NU1A0554",
                "17NU1A0555",
                "17NU1A0556",
                "18NU5A0501",
                "18NU5A0502",
                "18NU5A0503",
                "18NU5A0504",
                "18NU5A0505",
                "18NU5A0506",
                "18NU5A0507",
                "18NU5A0508",
                "18NU5A0509",
                "16NU1A0501",
                "16NU1A0502",
                "16NU1A0503",
                "16NU1A0504",
                "16NU1A0505",
                "16NU1A0506",
                "16NU1A0507",
                "16NU1A0508",
                "16NU1A0509",
                "16NU1A0510",
                "16NU1A0511",
                "16NU1A0512",
                "16NU1A0513",
                "16NU1A0515",
                "16NU1A0516",
                "16NU1A0518",
                "16NU1A0519",
                "16NU1A0520",
                "16NU1A0521",
                "16NU1A0522",
                "16NU1A0523",
                "16NU1A0524",
                "16NU1A0525",
                "16NU1A0527",
                "16NU1A0528",
                "16NU1A0529",
                "16NU1A0530",
                "16NU1A0531",
                "16NU1A0532",
                "16NU1A0533",
                "16NU1A0535",
                "16NU1A0536",
                "16NU1A0537",
                "16NU1A0538",
                "16NU1A0539",
                "16NU1A0540",
                "16NU1A0542",
                "16NU1A0543",
                "16NU1A0544",
                "16NU1A0545",
                "16NU1A0546",
                "16NU1A0547",
                "16NU1A0548",
                "16NU1A0549",
                "16NU1A0550",
                "16NU1A0551",
                "16NU1A0552",
                "16NU1A0553",
                "16NU1A0554",
                "16NU1A0555",
                "16NU1A0556",
                "16NU1A0557",
                "16NU1A0558",
                "16NU1A0559",
                "16NU1A0560",
                "16NU1A0561",
                "16NU1A0562",
                "16NU1A0564",
                "16NU1A0565",
                "16NU1A0566",
                "16NU1A0567",
                "16NU1A0568",
                "16NU1A0569",
                "16NU1A0570",
                "16NU1A0571",
                "16NU1A0572",
                "16NU1A0573",
                "16NU1A0574",
                "16NU1A0576",
                "16NU1A0577",
                "17NU5A0501",


        };
        private static final String[] CSEName = new String[]{
                "ADARI PRUDHVI JAYA KUMAR",
                "AGURU PRAVEEN KUMAR",
                "ALLAM SHASHI PREETHAM",
                "ARIYAPALLI VATSAVI",
                "ARSI LAKSHMI PRASANNA",
                "ASAM SIREESHA",
                "ASISH NIKHIL TERAPALLI",
                "ASHWIN KUMAR ROUT",
                "ATCHUTANNA SAI NIRMAL",
                "AVALA SAI KRISHNA PRAKASH YADAV",
                "BANDARU KUMARI",
                "B VINAY MAHARSHI",
                "BODANKI SRI RAMA RACHANA",
                "BODDETI RISHITHA",
                "BOLEM CHAITANYA JYOTHIKA",
                "CHALAMASETTY LAXMY CHARAN SAI",
                "CHALLA PAVANI KUMARI",
                "CHOLLANGI YASASWANI",
                "CHOPPALI BHARGAV",
                "DANDU PRAMODINI",
                "DANGETI ARUNA KUMARI",
                "DASARI PURNA SATISH",
                "DUMPA SATYAVENI",
                "DUNGA PRAVALLIKA",
                "GADI JASWANTH KUSHIL",
                "GAVARA YASODHA",
                "GAYATHRI SURESH",
                "GODDU MAHESH",
                "GOMPA PAVANI",
                "GORLE CHANDRA NAIDU",
                "GOURIPATTAPU SIVA VENKATA GOWTHAM",
                "GUDIYA DUKKI RAM SAHU",
                "GUNUPURU SOWJANYA",
                "HARSHAVARDHAN PANIGRAHI",
                "I HEMANTH REDDY",
                "I SAIKIRAN",
                "JENNA VYJAYANTHI",
                "KAMIREDDY TANOOJ SRI VENKATA NAIDU",
                "KARRI KUMAR NAIDU",
                "KATTA AARTHI",
                "KATTA BHARGAV",
                "KETAN JAIN",
                "KOILADA DEEPAK",
                "KOLATI LAXMI VENKATA SAI PRADEEP",
                "KOLLI GOVINDU",
                "KOLLI HARI KRISHNA",
                "KOLLI NIKHIL",
                "KOLUKULA KALYANI",
                "KOLUKULURI ARUN VARMA",
                "KONATHALA PRAVEEN KUMAR",
                "KORUPOLU SAHITHI",
                "KOSURU BALA GOVIND NATH",
                "KOTYADA ALEKHYA",
                "KUNDRAPU BHANU PRAKASH",
                "MADAKA PRIYA SANDHYA",
                "MAJJI LAVANYA",
                "MAJJI THANU SRI",
                "MANAM SIVA SAI",
                "MANDA SAI DHEERAJ",
                "MANDADI AVINASH",
                "MANDADI SEETHAMNAIDU",
                "MARADA RAMYA",
                "MARUPILLA JAHNAVI",
                "MEDIBOYINA DIVYA MANIKANTA",
                "MEDITHI KEERTHI SARVANI",
                "MOPADA MANASA",
                "MUDUNURI HEMA CHATURYA",
                "MUKKALA VAMSHI",
                "NABBA JEEVAN SAI",
                "NAGISETTI SAI KUMARI",
                "NAGULAPALLI GANESH MADHURI",
                "NELLI ARAVIND KUMAR",
                "GARIKINA NITHIN",
                "NYASAVAJHALA SWAROOP GANESH",
                "P MANOJ PRAKASH",
                "PABBIREDDY LALITHA",
                "PAKALAPATI SAI DEEPAK VARMA",
                "PALAVALASA PAVAN KALYAN",
                "PALIVELA YOGI PRIYA SAI",
                "PALLA DHARMA TEJA",
                "PALLA DIVYA",
                "PALURI DEVI",
                "PENTAKOTA BHUVAN SAMHITH",
                "PINAGADI SASI PREETHI",
                "PITTA NIKHIL",
                "POLAMARASETTY BHARGAVI",
                "POLIMERI SAI KUMAR",
                "POLIPALLI CHANDRA KIRAN",
                "POTHU SAI SURYA",
                "RAJANA JAHNAVI",
                "RALI MANIKANTA",
                "RAPARTHI VENKATA SATYA SRAVANTHI",
                "REDDY NAGA VENKATA SIVA",
                "ROHIT KUMAR MEESALA",
                "S HEMANTH REDDY",
                "SABBI LEELA VARA LAKSHMI",
                "SAMMENGI VIJAY",
                "SANA UMA",
                "SINGAMPALLI SINDHU SESHTNA",
                "SOWMYA PANDA",
                "SUDHEER KUMAR SEERA",
                "SUNDARA SUJIT VIRESH RAM MOHAN RAO",
                "SUNKARAPALLI VENKATA SANTOSH VALLI",
                "SUNKARI KRISHNAVENI",
                "SURUPALLI RAM AMRUTH RAJ",
                "T GURU KEERTHAN",
                "TATA HARIKA",
                "TEKI BHAVANI SHANKAR",
                "TENU BHAVYA SHREE CHALUMURI",
                "THERAPALLI UDAYA SRI",
                "UPPALA RAJESH KUMAR",
                "VALLE HARSHA VARDHAN",
                "VANAMADA GAYATHRI",
                "VANKAYALA KUMARI CHANDANA",
                "VANUMU VARDHINI",
                "YELEGA KUSHAL HEMANTH",
                "VENGALDASU GAYATHRI DEVI",
                "VISHNUVARJALA KUSUMALATHA",
                "VISSARAPU VENKATESH",
                "YEDDU HEMALATHA",
                "YELAMANCHILI KATYAYANI SUDARSINI",
                "VECHALAPU SAMPATH SAI SRILEKHA",
                "AMARA PADMAVATHI",
                "ANAKAPALLI SASIKIRAN",
                "ATHI SAI SARAN",
                "BALIVADA REETIKA",
                "BHAGI DURGA BHAVANI",
                "BHAVIRISETTY VENKATARAJU GUPTA",
                "BODDEDA HEMA SAI KUMAR",
                "BULUSU ANNAPURNA GAYATHRI AVANTHI",
                "CHADARAM ESTHER",
                "CHEEPULLA VENKATA ANUSHA",
                "CHUKKA RAJESH",
                "DATLA AKASH VARMA",
                "DATLA YASASWINI",
                "DEBASISH NANDI",
                "DONKINA AYYAPPA",
                "DONKINA VENKATA SAI VISWANADH",
                "GANDREDDI CHAITANYA",
                "GANGABATHULA YUVA SRI HARSHITHA",
                "GANTA RENUKA",
                "GONDESI RUDRA DEEPAK",
                "GORIPARTHI SAI LAKSHMI PHANI",
                "GORLI DILEEP",
                "GUNTURI DILEEP VARMA",
                "HARSHAVARDHAN SRINIVAS KARRI",
                "JULI KUMARI",
                "KARINGALU BHANU KIRTHI PRABHANJANA",
                "KAGUPATI SAMPATH RAJA RAGHUPATHI",
                "KALLA DINESH",
                "KALLA SAI PRANAVI",
                "KAMIREDDY SWATHI",
                "KANURI SAI KAIVALYA",
                "KOLLA TULASI",
                "KOLLI JAHNAVI",
                "KURAMARPU MADHURI",
                "LATHA KAPPA",
                "MACHERLA BHARGAVI",
                "MARGANA SHYAM SUNDAR",
                "MATTA TAABU",
                "MENDA RAMYA SRI",
                "MOLLA VAHED ABBAS",
                "MUNAGANTI SRAVANKUMAR",
                "PAMPANA RAMA JYOTHI",
                "PEMMISETTY DEEPAK",
                "PACHIPULUSU PAVITRA",
                "PINNINTI PRAVALLIKA",
                "RONGALI V S DEVIKA",
                "SADARAM NAYANA SAI",
                "SARIPALLI MOUNIKA",
                "SARKHIL MIRZA DUWAL ALI BAIG",
                "SUTAPALLI SUSHMA",
                "THIRUKKOVULLURU RICHA KUMARI",
                "TUMPALA RAGHUNATH",
                "VEMURI GAYATHRI",
                "VANAMALA SUBHAKARA RAO",
                "VANAPALLI MOUNIKA",
                "VARANASI LALITHA",
                "VARRI JHANSI RANI",
                "VASA LAKSHMI LAHARI",
                "VEMURI SARASWATHI",
                "BAVARAPU PRASANTH KUMAR",
                "JUM SAI BADARLA",
                "BHAIRI TIRUMALA",
                "BODDU BHAVANA",
                "BODDU BHAVYA",
                "BOYI BHAVANI UDAY KUMAR REDDY",
                "CHITTILLA VENKATA SOMANATH",
                "DADI PYDI DEEPAK",
                "DANTULURI TEJASWINI",
                "ENUMULA JYOTHI",
                "GUDEPU JOGESH BABU",
                "GANAPATHIRAJU HARSHA VARDHAN",
                "GORAPALLI BHAVANA",
                "GORLE BINDU MADHAVI",
                "GORLI DIVYA",
                "GOTTUMUKKALA POOJITHA",
                "GUNTREDDY PRADEEP CHANDRA",
                "GUTLAPALLI MOHAN RAO",
                "HARSHVARDHAN REDDY GUDLA",
                "IMMIDISETTY TEJASWINI",
                "KANISETTI BALAJI",
                "KARUMURU NAVEENA",
                "KSHATRI SRAVANI BAI",
                "MAJJI SHANMUKH RAO",
                "MALLA DHARMA TEJA",
                "MALLA JITENDAR BALAJI",
                "MUKALA MANOJ KUMAR",
                "MURUKURTHI TEJESWARI",
                "NAMMI RENUKA",
                "PANDURI LALITHA LIKITHA",
                "PILLA SRAVANI",
                "PINNAMARAJU KEERTHI",
                "PINNAMARAJU UMA",
                "POLAKI AKHILA",
                "PRAYAGA KRISHNA SARANYA",
                "PUREDDY VIJAYALAKSHMI",
                "RAVADA KALYAN",
                "RAGHUPATRUNI VENKATA HARSHA VARDHAN",
                "SADHANALA GYANA NIKITHA",
                "SAMAREDDY FRANCIS",
                "SAPPA SATYA SAI NAGA MANISHA",
                "TELU SUDHAKAR",
                "TRINADHULA SATISH",
                "VANGALAPUDI GNANA DEEPTHI",
                "VIJAY KUMAR PRASAD",
                "VUYYURU LAKSHMI SOWJANYA",
                "BONU SIVA SAI",
                "DOKI MUKESH",
                "KODAGALA VENKATA SAI KRISHNA",
                "MIRAPA ROHIT",
                "NAKKINA SAI",
                "PENTAPALLI ANITHA",
                "RAPARTHI PAVAN KALYAN",
                "RAYI PRIYANKA",
                "SENAPATHI GANESH KUMAR",
                "TAMADA JEEVAN SEKHAR",
                "VURIVI NARENDRA SIVA KESAVA",
                "AKULA SIVA VENKATA RAJESH",
                "ALLURI RESHMA BHAVANI",
                "AYALASOMAYAJULA VENKATA ADITHYA",
                "BADUGU MEGHANA VERONICA",
                "BALIJI LAKSHMI PRASANNA",
                "BASAVA NARASIMHARAJU",
                "BODDAPALLI RAVI KUMAR",
                "BODDU PREM KUMAR",
                "BRUNDAVANAM HARIKA",
                "CHALUMURI DEEPAK",
                "DASARI JHANSI LAKSHMI",
                "D SAI VAISHNAVI",
                "ETI NIVEDITHA",
                "GADIRAJU SAI MANOGYA",
                "GANDREDDI SOWMYA",
                "GUDE URMILA",
                "JINNALA TIRUBALA VELANGINI ROJA SYAMALA",
                "JOGA ANUSHA",
                "KALLA KAVYA",
                "KALLAPALLI JAGADEESH",
                "KILAPARTHY CHAKRAVARTHY",
                "KORIPALLI ROSHINI",
                "KOTA JAYARAM",
                "LANKA ASHOK KUMAR",
                "MALIPEDDI NIKHITHA",
                "MALLIPUDI RAMYA SRI",
                "MAMIDIPALLI VENKATA KRISHNA SAI PRAVEEN",
                "MANDA HARISH KUMAR",
                "MATHI ASHOK SAGAR",
                "MUGGU LAKSHMI MANASWINI",
                "MUKUL KUMAR SHARMA",
                "NAMBURI NIKHIL VARMA",
                "NAMRATA SINGH",
                "PAPPALA VINAY KUMAR",
                "PRASHANT MISHRA",
                "RELLI SANDHYA",
                "RONGALA HARISH",
                "RONGALI USHA",
                "SAIDU LAKSHMI SAI PRASANNA",
                "SATYAVARAPU MANASA",
                "SEELAM SRIKARI",
                "SEERAPU SANDHYA RANI",
                "SETTI MARVILLOUS KIRAN",
                "SURESH MOIDA",
                "SURISETTY BINDU MADHAVI",
                "TELAPROLU JOSHI SANKAR",
                "THANAVARAPU PAVANI",
                "THUMPALA LAKSHMI KUMARI",
                "VADDADI SASIKALA",
                "VADLAMANI SUBRAHMANYA TEJASWI",
                "VARANASI VANI",
                "VEDULA SAI AMRUTHA",
                "VOBBILISETTY CHANDRA KRISHNA",
                "YELLAPU DURGA SAI CHANDU",
                "AMEREPALLI BHASKER RAO",
                "APPALABATHULA MONIKA",
                "CHILLIBOINA RANI",
                "CHINTALA KAVYASRI",
                "CHUKKALA BINDU PRIYA",
                "GANTLA THULASI TIRUMALESWARI",
                "JAMI TEJA MANI",
                "MOKARA HEMALATHA",
                "VANAMU SATYA AKHILA",
                "ADARI GOWTHAM",
                "BALIVADA VAMSI SAIRAM",
                "BALLA ARUN KUMAR",
                "BAVIRIPUDI SIVAKUMAR",
                "BOBBA HARI PRIYA",
                "BODDETI GANESH KUMAR",
                "BODDU USHA RANI",
                "BUGATHA SAI SUDHA",
                "CHAPPAGADDI BHARGAVI SOUMYA",
                "CHIKKALA BHANUKUMAR",
                "DEVABHAKTINI VAMSIKRISHNA",
                "DADI SATYA DEEP",
                "DANTHULURI SIRI CHANDANA VARMA",
                "DHARMIREDDY SAI SEKHAR",
                "DODDI LAABITHA",
                "G.VENKATA SAI DEEPIKA",
                "GOLAGANI SAISRAVANI",
                "GONTHINA KUMAR SWAMY",
                "GUNTUPU SOWJANYA",
                "GURAJADA PRANEETH",
                "GUTHULA DURGA BHAVANI SHANKAR",
                "JUTTADA DINESH VENKATA MANOHAR",
                "KOTYADA USHA",
                "KALIDINDI CHANDINI",
                "KARANAM SANDEEP",
                "KARIDLA HIMANIDEVI",
                "KARISHMA ACHARYA",
                "KARRI YEHEZEKIEL",
                "KOLLURU NAGA VASAVI RAMYA",
                "KONDA DIVYA",
                "KUPPA LOKESWAR KAUSHIK SRAVAN",
                "MALIREDDY DEVIPRASAD",
                "MANDAPATI SATYA VENKATA SAROJINI DEVI",
                "MATALA ARUNDATHI",
                "MAVIDI VENKATA SAI KANTH",
                "MD SHAIR ALI",
                "MUKKA GOWRI",
                "MUKKA TULASI LAKSHMANATH",
                "MUKKA TULASI RAMYA",
                "MULA DIVYA SRI",
                "MURIPINDI DINESH",
                "KANDULA NAVEEN",
                "NIRMALA DOLAI",
                "PULAGAM HIMAJA",
                "PADEM PERINDHA VALLI",
                "PAKALAPATI SATYA SURYA LOHITH VARMA",
                "PALLAPOTU NAGA VENKATA PREM SAI RAJ KUMAR",
                "PATOJU DATTA VENKATA SAI RAM",
                "PENMETSA BALARAMA SHEKAR PAVAN VARMA",
                "PENTAKOTA NEELIMA SOWNDARYA SAI",
                "PERI SAI PRASANTHI",
                "PINNAMRAJU ROHINI DEVI",
                "PINNAMARAJU ROJA",
                "POLAMARASETTI SRAVANTHI",
                "PONNURU VENKATA MANSA",
                "PONTHAPALLI RAVITEJA",
                "POPURI SAI GANESH",
                "RAMINENI DIVYA",
                "RAVADA MOHAN RAO",
                "SATHAKA MOUNIKA",
                "SABBI JAYA LAKSHMI",
                "SEETHAMRAJU SAI SIVA RAM",
                "SIRIKI VASANTHA",
                "TANAVARAPU SAI DIWAKAR",
                "TANUKU AKHILA NAGAPARIMALA",
                "THATRAJU GEETHANJALI",
                "VANDRASI SUSMITHA MANIMALA",
                "VASAMSETTY SRI LIKITA",
                "VENNALA HEMALATHA",
                "VEPADA UMADEVI",
                "MAJJI VAMSI SAI KRISHNA",

        };

        @Override
        protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_cse_add);
            getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
                txtname = findViewById(R.id.name);
                txtroll = findViewById(R.id.rollno);
                sec = findViewById(R.id.section);
                btn = findViewById(R.id.submit);

                ArrayAdapter<String> adapter = new ArrayAdapter<>(this,
                        android.R.layout.simple_list_item_1, CSE);
                txtroll.setAdapter(adapter);
                ArrayAdapter<String> adapter1 = new ArrayAdapter<>(this,
                        android.R.layout.simple_list_item_1, CSEName);
                txtname.setAdapter(adapter1);


        }


        @Override
        public void onBackPressed() {
                super.onBackPressed();
                finish();
        }


        public void submit(View view) {
                String url = "http://192.168.6.139/insertcse.php";
                RequestQueue myrequest = Volley.newRequestQueue(this);
                StringRequest stringRequest = new StringRequest(Request.Method.POST, url, new Response.Listener<String>() {
                        @Override
                        public void onResponse(String response) {
                                Toast.makeText(getApplicationContext(), response, Toast.LENGTH_LONG).show();

                        }
                },
                        new Response.ErrorListener() {
                                @Override
                                public void onErrorResponse(VolleyError error) {
                                        Toast.makeText(getApplicationContext(), error.getMessage().toString(), Toast.LENGTH_LONG).show();
                                }
                        }) {
                        @Override
                        protected Map<String, String> getParams() throws AuthFailureError {
                                Map<String, String> map = new HashMap<String, String>();
                                map.put("name", txtname.getText().toString());
                                map.put("rollno", txtroll.getText().toString());
                                map.put("section", sec.getText().toString());
                                return map;
                        }
                };

                if (TextUtils.isEmpty(txtroll.getText().toString())) {
                        txtroll.setError("required roll");

                }

                if (TextUtils.isEmpty(txtname.getText().toString())) {
                        txtname.setError("required name");
                }
                if (TextUtils.isEmpty(sec.getText().toString())) {
                        sec.setError("required section");

                }
                else {
                        Toast.makeText(cseAdd.this, "details saved", Toast.LENGTH_SHORT).show();

                        myrequest.add(stringRequest);
                }
        }
}
