package com.example.d;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.view.WindowManager;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.Toast;

import com.android.volley.AuthFailureError;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;

import java.util.HashMap;
import java.util.Map;

public class eceAdd extends AppCompatActivity {
    AutoCompleteTextView txtname, txtroll, sec;
    Button btn;

    private static final String[] ECE = new String[]{

            "19NU1A0401",
            "19NU1A0402",
            "19NU1A0403",
            "19NU1A0404",
            "19NU1A0405",
            "19NU1A0406",
            "19NU1A0407",
            "19NU1A0408",
            "19NU1A0409",
            "19NU1A0410",
            "19NU1A0411",
            "19NU1A0412",
            "19NU1A0413",
            "19NU1A0414",
            "19NU1A0415",
            "19NU1A0416",
            "19NU1A0417",
            "19NU1A0418",
            "19NU1A0419",
            "19NU1A0420",
            "19NU1A0421",
            "19NU1A0422",
            "19NU1A0423",
            "19NU1A0424",
            "19NU1A0425",
            "19NU1A0426",
            "19NU1A0427",
            "19NU1A0428",
            "19NU1A0429",
            "19NU1A0430",
            "19NU1A0431",
            "19NU1A0432",
            "19NU1A0433",
            "19NU1A0434",
            "19NU1A0435",
            "19NU1A0436",
            "19NU1A0437",
            "19NU1A0439",
            "19NU1A0440",
            "19NU1A0441",
            "19NU1A0442",
            "19NU1A0443",
            "19NU1A0444",
            "19NU1A0445",
            "19NU1A0446",
            "19NU1A0447",
            "19NU1A0448",
            "19NU1A0449",
            "19NU1A0451",
            "19NU1A0452",
            "19NU1A0453",
            "19NU1A0454",
            "19NU1A0455",
            "19NU1A0456",
            "19NU1A0457",
            "19NU1A0458",
            "19NU1A0459",
            "19NU1A0460",
            "19NU1A0461",
            "19NU1A0462",
            "19NU1A0463",
            "19NU1A0464",
            "19NU1A0465",
            "19NU1A0466",
            "19NU1A0467",
            "19NU1A0468",
            "19NU1A0469",
            "19NU1A0470",
            "19NU1A0471",
            "19NU1A0472",
            "19NU1A0473",
            "19NU1A0474",
            "18NU1A0401",
            "18NU1A0402",
            "18NU1A0403",
            "18NU1A0404",
            "18NU1A0405",
            "18NU1A0406",
            "18NU1A0407",
            "18NU1A0408",
            "18NU1A0409",
            "18NU1A0410",
            "18NU1A0411",
            "18NU1A0412",
            "18NU1A0413",
            "18NU1A0414",
            "18NU1A0415",
            "18NU1A0416",
            "18NU1A0417",
            "18NU1A0418",
            "18NU1A0419",
            "18NU1A0420",
            "18NU1A0421",
            "18NU1A0422",
            "18NU1A0423",
            "18NU1A0424",
            "18NU1A0425",
            "18NU1A0426",
            "18NU1A0427",
            "18NU1A0428",
            "18NU1A0429",
            "18NU1A0430",
            "18NU1A0431",
            "18NU1A0432",
            "18NU1A0433",
            "18NU1A0434",
            "18NU1A0435",
            "18NU1A0436",
            "18NU1A0437",
            "18NU1A0438",
            "18NU1A0439",
            "18NU1A0440",
            "18NU1A0441",
            "18NU1A0444",
            "18NU1A0445",
            "18NU1A0446",
            "18NU1A0447",
            "18NU1A0448",
            "18NU1A0449",
            "18NU1A0450",
            "18NU1A0451",
            "18NU1A0452",
            "18NU1A0453",
            "18NU1A0454",
            "18NU1A0455",
            "18NU1A0456",
            "18NU1A0457",
            "18NU1A0458",
            "18NU1A0459",
            "18NU1A0460",
            "18NU1A0461",
            "18NU1A0462",
            "18NU1A0463",
            "18NU1A0464",
            "18NU1A0465",
            "18NU1A0466",
            "18NU1A0467",
            "18NU1A0468",
            "18NU1A0469",
            "18NU1A0470",
            "18NU1A0471",
            "18NU1A0472",
            "18NU1A0473",
            "18NU1A0474",
            "18NU1A0475",
            "18NU1A0476",
            "18NU1A0477",
            "18NU1A0478",
            "18NU1A0479",
            "19NU5A0401",
            "19NU5A0402",
            "19NU5A0403",
            "19NU5A0404",
            "19NU5A0405",
            "19NU5A0406",
            "19NU5A0407",
            "19NU5A0408",
            "19NU5A0409",
            "19NU5A0410",
            "19NU5A0411",
            "19NU5A0412",
            "19NU5A0413",
            "19NU5A0414",
            "19NU5A0415",
            "19NU5A0416",
            "19NU5A0417",
            "19NU5A0418",
            "19NU5A0420",
            "19NU5A0421",
            "19NU5A0422",
            "19NU5A0423",
            "19NU5A0424",
            "19NU5A0425",
            "19NU5A0426",
            "19NU5A0427",
            "19NU5A0428",
            "19NU5A0429",
            "19NU5A0430",
            "17NU1A0401",
            "17NU1A0402",
            "17NU1A0403",
            "17NU1A0404",
            "17NU1A0405",
            "17NU1A0406",
            "17NU1A0407",
            "17NU1A0409",
            "17NU1A0410",
            "17NU1A0411",
            "17NU1A0412",
            "17NU1A0413",
            "17NU1A0414",
            "17NU1A0415",
            "17NU1A0416",
            "17NU1A0417",
            "17NU1A0418",
            "17NU1A0419",
            "17NU1A0420",
            "17NU1A0421",
            "17NU1A0422",
            "17NU1A0423",
            "17NU1A0424",
            "17NU1A0425",
            "17NU1A0426",
            "17NU1A0428",
            "17NU1A0430",
            "17NU1A0432",
            "17NU1A0433",
            "17NU1A0434",
            "17NU1A0435",
            "17NU1A0436",
            "17NU1A0437",
            "17NU1A0438",
            "17NU1A0439",
            "17NU1A0440",
            "17NU1A0441",
            "17NU1A0442",
            "18NU5A0401",
            "18NU5A0402",
            "18NU5A0403",
            "18NU5A0404",
            "18NU5A0405",
            "18NU5A0406",
            "18NU5A0407",
            "18NU5A0408",
            "18NU5A0409",
            "18NU5A0410",
            "18NU5A0411",
            "18NU5A0412",
            "18NU5A0413",
            "18NU5A0414",
            "18NU5A0415",
            "18NU5A0416",
            "18NU5A0417",
            "18NU5A0418",
            "18NU5A0419",
            "18NU5A0420",
            "18NU5A0421",
            "16NU1A0401",
            "16NU1A0402",
            "16NU1A0404",
            "16NU1A0405",
            "16NU1A0406",
            "16NU1A0407",
            "16NU1A0408",
            "16NU1A0409",
            "16NU1A0410",
            "16NU1A0411",
            "16NU1A0412",
            "16NU1A0413",
            "16NU1A0414",
            "16NU1A0415",
            "16NU1A0416",
            "16NU1A0417",
            "16NU1A0418",
            "16NU1A0419",
            "16NU1A0420",
            "16NU1A0421",
            "16NU1A0422",
            "16NU1A0423",
            "16NU1A0425",
            "17NU5A0401",
            "17NU5A0402",
            "17NU5A0403",


    };
    private static final String[] ECEName = new String[]{

            "ACHARYA MADHUKAR",
            "AGURU VINOD KUMAR",
            "ALLANKI BHANUPRAKASH",
            "ANUPOJU NAGENDRA KUMAR",
            "BANKA NARESH",
            "BHAGI THANVI TRILOCHANA",
            "CHALLA KANAKA MAHA LAXMI",
            "CHEKKA MANIKANTA GUPTA",
            "CHENNAPURAM PAVANI",
            "CHINTHALAPATI SRIYA VARMA",
            "DANGETI PAVANI PRATHYUSHA",
            "DANGETI PUSHPALATHA",
            "DOGGA MANISHA",
            "EATI HARINI SRI VYSHNAVI",
            "GALLA REVATHI DEVI",
            "GAVARA SAILENDRA",
            "GIDUTURI SURYA VENKATA DURGESH",
            "GULIVINDALA KHUSHBU",
            "JAMI KIRAN KUMAR",
            "JANAPAREDDI MOUNIKA",
            "JAYANTH PRAJAPATHI",
            "K MANISH",
            "KALYAN NEMANI",
            "KARAKAVALASA HEMANTH PATNAIK",
            "KATTA BALA VEERA SWAMY",
            "KOKKIRIGEDDA AAKASH",
            "KOLLA MOUNIKA",
            "KORUKONDA SIRISHA",
            "KOTYADA TRIVENI",
            "KUPPALA PAVAN KALYAN",
            "LAKKARAJU PAVAN KUMAR",
            "LANKA DEEPAKVARAPRASAD",
            "MAJHI LIKHITHA",
            "MANDALA DURGA SRI PRASAD",
            "MANDAPATI SANJAY VARMA",
            "MANTHA VENKATA KRISHNA SANJAY",
            "MEDISETTI TEJESH",
            "MEGHAMS NAGA SAI CHINTALAPUDI",
            "MOPADA MOUNIKA",
            "NEKKANTI SAI NAGA BHARGAV",
            "NUNELA SAI KUMAR",
            "PALLA HEMANTH",
            "PALLA PREM",
            "PANAUT ROHIT NAIR",
            "PANCHIREDDY LOKESWARA RAO",
            "PANDULA MONICA VENKATA SAI ROOPA",
            "PERI VENKATA PAVAN SAKETH",
            "PIDUGU SANDEEP",
            "PONNADA SAI TEJA",
            "POTHARAJU SANJU VARA PRASAD",
            "PREETI DAS",
            "PULAKALA GANESH",
            "PUREDLA SHANMUKH SAGAR KUMAR",
            "RAI ASHA DEEPIKA",
            "RAJANA MOULIKA",
            "RAYAVALASA SAI VENKATA PREETHAM",
            "SADARAM JAYASRI",
            "SAGI TEJASWINI",
            "SENA ANIL",
            "SHAIK NAWAZ SHAREEF",
            "SIGADAM PRAVALLIKA",
            "SONABHA PREETHI",
            "T. HARI HEMANTH",
            "TAMMINANA AVINASH",
            "VALLI THARUN KUMAR",
            "VANGALA MOUNIKA",
            "VATSAVAYI S V S SATYANARAYANA RAJU",
            "VEMPALLI MADHU SAI",
            "VISHAL SANTHARAM JADAV",
            "VUDUKULA KALYANI",
            "YANNAMREDDY NARASIMHA REDDY",
            "YEDUVAKA UKESH BABU",
            "AJITH PANDA",
            "AKKARABOINA VANDHANA",
            "ALLADA CHAITANYA SRAVANTHI",
            "ALLADA KIRAN",
            "ANNASAMUDRAM VINAYASREE",
            "APPARI KARTHIK",
            "ATTA SATYA GIRISH",
            "AVVA SAI LAKSHMI",
            "BAGGAM SURYA VENKATA SATYANARAYANA",
            "BANDARU DIVYA",
            "DANTULURI NAGA SRAVANI",
            "DHARMAVARAPU ANEESHA",
            "DUKKI TEJA",
            "EROTHI MEGHANA",
            "GADI VENKATA NAGA MANI KRISHNA",
            "GANDI RAMESH",
            "GELLI VEERA VENKATA VAMSI",
            "GUNNABATHULA HARSHAPRIYA",
            "JEERU ROJA RAMANI",
            "KALIDINDI SAI CHARAN RAJU",
            "KALLA GOVARDHANI DEEPIKA",
            "KALPATAPU USHASRI",
            "KANISETTI SIVANI",
            "KANITHI LEELA SAI KOTESWARI",
            "KODUKULA GAYATHRI DEVI",
            "KOLUKULOORI TEJA SATYA SASHANKA VARMA",
            "KOSURU PUSHKALA",
            "KUTTUM MADHU SREE",
            "MAKKUVA SAI VINAY",
            "NAVEEN KUMAR GORIVILLI",
            "NUNNA KAVYA",
            "JAGANNADHA SRIKAR NYAYAPATHI",
            "PAKKI JOHNA SUDEEPA PATNAIK",
            "PASUMARTHI SWARNAMALA",
            "PATHIVADA JYOTHI",
            "POTNURU SAI TEJA",
            "RAJANA TEJA",
            "RANGISETTI GOPICHAND",
            "SALADI HEMALATHA",
            "SALAPU YASWANTH KUMAR",
            "SESETTI GAYATHRI",
            "SURAVARAPU RAJA RAJESWARI LAVANYA KUMARI",
            "TIRUMALARAJU VIJAYA BHASKARA VARMA",
            "VANAMOJU YASWANT SAI PAWAN",
            "VANDRANGI SAI PREETHI",
            "VEMULA R V S KARTHIK",
            "VYDA JAYANTH KUMAR",
            "YARABALA HARIKA",
            "ALLA RUTHIK KUMAR",
            "AVUGADDI BHAVANI",
            "BANDARU SRI KRISHNA",
            "BODDEDA NEERAJ",
            "CHAPA SAI KISHORE",
            "DHARMANA HIMA VARSHINI",
            "GEDALA PRUDHVI SAI KUMAR",
            "GEDDA NITIN SATYA",
            "IRRA JITHENDRA",
            "KANDI JYOTHI",
            "KASTURI SAI KIRAN",
            "KORADA RAMANA",
            "MARADANA KIRAN",
            "MADDILA JASWANTH",
            "M JYOTSNA",
            "MUMMANA SYAMALA",
            "PENTAKOTA SRAVANI",
            "POLAMARASETTI SANJAY",
            "PRETHWIRAJ SREEBAMA VADAKUMPURAM",
            "RANDHI PAVAN KUMAR",
            "SACHIN YADAV",
            "SANKILI PAVANI",
            "SARAGADAM SIRISHA",
            "SUNKARI RAMESH NAIDU",
            "VADALI VENKATA SATYA SAI SRIKANTH",
            "VANTAKU RAMESH",
            "VARADAPUREDDY MANOHAR",
            "VELUSURI DURGA KANAKA MAHA LAKSHMI",
            "YENNI AKHIL",
            "ADIREDDI HARIKA",
            "ADIREDDI LAVANYA",
            "ALUGOLU RAM KUMAR",
            "BAYANI KAVYA",
            "BHEEMARASETTI NANDINI",
            "CHANDAKA PAVAN",
            "CHANDAKA SURYANARAYANA",
            "CHEPURI RAMAKRISHNA",
            "CHOPPA GEETHASRI BHAVANI",
            "DADI JAGADEESH",
            "DALIBOYINA TILOTHAMA YADAV",
            "DEVA DIVYA",
            "ERUGULU RAMYA",
            "GALLA VENU VARDHAN",
            "GUDE JAYASREE",
            "JADA HARISH KUMAR",
            "KALAMATA HARI KRISHNA",
            "KANDIPALLI ANAND KUMAR",
            "KINTHADA HARIKA DEVI",
            "KOTTANA SRIKANTH",
            "NEBARTHI SRAVANI",
            "PENTAKOTA PRAVEEN",
            "POLIMERA VASHIKA",
            "PONAGANTI YASWANTHKUMAR",
            "POTHRAKANDI KOTESWARA RAO",
            "PULLELA BALA SAI SURYA KAMESWARI SWETHA",
            "PUTTA SUJITH",
            "RAMASETTI SOWJANYA",
            "VARANASI PRAVEEN",
            "ANGATA SHIVA PRASAD",
            "ASAM BHARGAV REJA",
            "BOBBARA NARESH",
            "BODDEPALLI PRAVEEN",
            "BODDU VENKATA KRISHNA MOHAN",
            "BOJANKI SURESH",
            "BOMMA UDYAYINI",
            "CH.VINAY",
            "CHALUMURI BHANU CHANDHAR",
            "DUSI VICTORIYA RANI",
            "EAGALA VIJAYA KUMAR",
            "ETHAKOTA KISHORE",
            "GARIKINA HESA",
            "GAVARA DIVYA SRIRAM",
            "GORAPALLI POORNA CHANDRA RAJU",
            "INDUKURI HARI DHAR VARMA",
            "KELAM BHAVANSAI KUMAR",
            "KELAM MEGHANA",
            "KOLLA VENKATA LAKSHMI KANTHARAO",
            "KORUBILLI GUNASAI",
            "KOYILADA MOHAN KUMAR",
            "MAJJI BHANU PRAKASH",
            "MIDATHANA CHANDRASEKHAR",
            "MOHAMMAD HAKKIM ABDUL",
            "NAGISETTY CHAITANYA",
            "NIMMADA SAI CHAITANYA",
            "PAVAN KUMAR SAHU",
            "POTHAPRAGADA RAZKUMAR",
            "PUDI AJAY KUMAR",
            "PULAGAM HARITHA",
            "PULLARI BHARGAVI SAI PUJITHA",
            "RAJANA GOUTAM",
            "REDDI MAHESH KUMAR",
            "REESU THARUN VARDHAN",
            "SARAGADM VENUPRIYA",
            "SATHIVADA SAI KUMAR",
            "VADDADI VENKATA RAJU",
            "VECHALAPU DHARMA TEJA",
            "ANGA PRIYANKA",
            "BEELA HYMAVATHI",
            "BHAIRI SOWJANYA",
            "BHEEMARASETTY JYOTHI",
            "DABBI KIRANKUMAR",
            "KANDULA BHAVANI",
            "KODUKULA PRAVEEN KUMAR",
            "PENTAKOTA YASWANTH",
            "PEDIREDLA GANESH KUMAR",
            "PASUMARTHI VENKATESH",
            "PEDIREDLA HINDUJA",
            "PONDARI CHANDRA SAI VENKATA SRINIVAS",
            "RAPETI YOGITHA",
            "SABBAVARAPU CHANDRAKALA",
            "SEERAM SRIKANTH",
            "SIVALANKALA ANITHA",
            "SIVALANKALA ISHWARYA",
            "SYED NOORJAHAN",
            "THURUPATI INDIRA DEVI",
            "UPPALA JAYA BHARATHI",
            "YADLAPALLI DILEEP",
            "BADAM BHARGAVI",
            "BANDARU YERNI REVATH SAI",
            "ELLAPU PADMAVATHI",
            "GANISETTI USHASRI",
            "GORLE NAVEEN KUMAR",
            "JAGARAPU BHARGAVI",
            "KANAKAM SAI LEELA",
            "KANDULA BHARATH",
            "KONKIPUDI VISHNU PRIYA",
            "KOTYADA LOKESH",
            "LATHA KONA",
            "MANTHA SURYA SRUTHI",
            "OMMI SARVANI",
            "POTTA SURYA TEJA BAHUDOOR GUPTA",
            "PUTTUPU SASIKANTH",
            "RAMA KONA",
            "ROKKAM THARUN BABU",
            "SABBAVARAPU MOHINI",
            "SAGI VAMSI",
            "SIDAGAM BALA SARASWATHI",
            "SIRIKI RENUKA",
            "TELU V.S.S.SAIKISHAN",
            "VEERAMALLA ROHINI",
            "ALLU TEJASWEE",
            "KALEPU HARIKRISHNA",
            "LENKA POORNIMA",

    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ece_add);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        txtname = findViewById(R.id.name);
        txtroll = findViewById(R.id.rollno);
        sec = findViewById(R.id.section);
        btn = findViewById(R.id.submit);

        ArrayAdapter<String> adapter = new ArrayAdapter<>(this,
                android.R.layout.simple_list_item_1, ECE);
        txtroll.setAdapter(adapter);
        ArrayAdapter<String> adapter1 = new ArrayAdapter<>(this,
                android.R.layout.simple_list_item_1, ECEName);
        txtname.setAdapter(adapter1);

    }

    @Override
    public void onBackPressed() {
        super.onBackPressed();
        finish();
    }

    public void submit(View view) {
        String url = "http://192.168.6.139/insertece.php";
        RequestQueue myrequest = Volley.newRequestQueue(this);
        StringRequest stringRequest = new StringRequest(Request.Method.POST, url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                Toast.makeText(getApplicationContext(), response, Toast.LENGTH_LONG).show();

            }
        },
                new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        Toast.makeText(getApplicationContext(), error.getMessage().toString(), Toast.LENGTH_LONG).show();
                    }
                }) {
            @Override
            protected Map<String, String> getParams() throws AuthFailureError {
                Map<String, String> map = new HashMap<String, String>();
                map.put("name", txtname.getText().toString());
                map.put("rollno", txtroll.getText().toString());
                map.put("section", sec.getText().toString());
                return map;
            }
        };
        if (TextUtils.isEmpty(txtroll.getText().toString())) {
            txtroll.setError("required roll");

        }

        if (TextUtils.isEmpty(txtname.getText().toString())) {
            txtname.setError("required name");
        }
        if (TextUtils.isEmpty(sec.getText().toString())) {
            sec.setError("required section");

        } else {
            Toast.makeText(eceAdd.this, "details saved", Toast.LENGTH_SHORT).show();

            myrequest.add(stringRequest);
        }
    }
}


